name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]  # Adjust if your default branch is not 'main'
  workflow_dispatch:  # Allows manual trigger from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"     # or any other LTS version you prefer
          cache: "npm"          # enable npm caching
          cache-dependency-path: "east-feast-site/package-lock.json"

      # Step 4: Install dependencies using npm
      - name: Install Dependencies
        run: npm ci
        working-directory: east-feast-site
        shell: bash

      # Step 5: Build the Next.js app
      #         Next.js 15 uses "output: export" in next.config.ts to generate ./out
      - name: Build Next.js App
        run: npm run build
        working-directory: east-feast-site
        shell: bash

      # Step 6: Upload the `out` folder as an artifact for the next job to use
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: east-feast-site/out  # the output directory for static export

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # Must wait for 'build' job to finish
    steps:
      # Step 7: Deploy to GitHub Pages using the artifact from the 'build' job
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
